GET http://localhost:5000/users/id/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJjdXN0b21lck4iLCJ1c2VySWQiOjEsInJvbGUiOiJjdXN0b21lciIsImxhc3ROYW1lIjoiY3VzdG9tZXJMIiwiYXZhdGFyIjoiYW5vbi5wbmciLCJkaXNwbGF5TmFtZSI6ImN1c3RvbWVyRE4iLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiY3VzdG9tZXJAbWFpbC5jb20iLCJyYXRpbmciOjAsImlhdCI6MTY5NDI0MjIzNywiZXhwIjoxNjk0MjQ1ODM3fQ.tz67sQxNmitvsKaUJo0huCSN_7bju6gA7uBzwEDscCs